name: dumdeedum
description: A Gemini browser, evolving from Deedum

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2025.0511.2313+1

environment:
  sdk: '^3.2.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.4.2
  path: ^1.9.1
  qr: ^3.0.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  app_links: ^6.4.0
  extended_text: ^15.0.2
  flutter_markdown: ^0.7.7+1
  asn1lib: ^1.6.4
  x509: 0.2.4+3
  crypto: ^3.0.6
  punycode: ^1.0.0
  string_validator: ^1.1.0
  basic_utils: ^5.4.2
  provider: ^6.1.5
  riverpod: ^2.6.1
  fast_immutable_collections: ^11.0.4
  flutter_riverpod: ^2.6.1
  toggle_switch: ^2.3.0
  pointycastle: ^4.0.0
  terminal_color_parser:
    git:
      url: https://github.com/jchaves/terminal_color_parser_dart
      ref: feature/rgb_support

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

  fonts:
    - family: Source Serif Pro
      fonts:
        - asset: assets/SourceSerifPro-Light.otf
          weight: 300
          style: normal
        - asset: assets/SourceSerifPro-LightIt.otf
          weight: 300
          style: italic
        - asset: assets/SourceSerifPro-Regular.otf
          weight: 400
          style: normal
        - asset: assets/SourceSerifPro-It.otf
          weight: 400
          style: italic
        - asset: assets/SourceSerifPro-Bold.otf
          weight: 700
          style: normal
        - asset: assets/SourceSerifPro-BoldIt.otf
          weight: 700
          style: italic
    - family: DejaVu Sans Mono
      fonts:
        - asset: assets/DejaVuSansMono.ttf

flutter_icons:
  image_path_android: "assets/launcher_android.png"
  image_path_ios: "assets/launcher_ios.png"
  android: true
  ios: true
